version: "3"

services:

  server:
    container_name: server
    image: trieulevan/server
    environment:
      - PORT={{ port }}
    network_mode: host
    restart: unless-stopped

  client:
    container_name: client
    image: trieulevan/client
    environment:
      - PORT={{ port }}
      - IP_SERVER={{ ip_server }}
    network_mode: host
    restart: unless-stopped